name: Deploy Shiny App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install packages
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev
        R -e 'install.packages(c("shiny", "rsconnect", "ggplot2"))'
        
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_ACCOUNT_NAME: ${{ secrets.SHINYAPPS_ACCOUNT_NAME }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        R -e 'rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT_NAME"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
        R -e 'rsconnect::deployApp(appName = "my-shiny-app")'
